######################################################################
##
## Filename: bitRevOrder_SM_Top_bitRevOrder_SM_Top_sch_tb.udo
## Created on: Mon Apr 30 9:10:56 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
