######################################################################
##
## Filename: bitrevorder_test_top2_bitrevorder_test_top2_sch_tb.udo
## Created on: Mon Apr 30 3:25:44 AM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
