######################################################################
##
## Filename: bitRevRam.udo
## Created on: Mon Apr 30 8:36:54 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
