######################################################################
##
## Filename: COS_LUT_tb.udo
## Created on: Sun Apr 29 11:59:56 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
