######################################################################
##
## Filename: counter9bit_tb.udo
## Created on: Mon Apr 30 1:38:55 AM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
