######################################################################
##
## Filename: inputData_RRAM_tb.udo
## Created on: Sun Apr 29 9:59:35 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
