######################################################################
##
## Filename: test_test_sch_tb.udo
## Created on: Tue May 01 2:44:36 PM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
