######################################################################
##
## Filename: test_tb.udo
## Created on: Mon Apr 30 12:50:36 AM Pacific Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
